# Generated by Django 3.2.7 on 2021-10-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211022_2257'),
        ('dashboard', '0003_auto_20211023_1558'),
    ]

    operations = [
    ]
